version: '3.8'
services:
  bug_simulator:
    build: ./services/bug_simulator
    ports:
      - "5001:5001"
    networks:
      - chaosnet

  log_collector:
    build: ./services/log_collector
    ports:
      - "6001:6001"
    networks:
      - chaosnet

  health_monitor:
    build: ./services/health_monitor
    networks:
      - chaosnet

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - chaosnet

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - chaosnet

networks:
  chaosnet:
